vim.g.mapleader = ' '
vim.keymap.set("n", "<leader>u", require("undotree").open)
vim.keymap.set("i", "", "<C-S-H>", { desc = "Solution for xterm" })
vim.keymap.set({ "n", "v" }, "j", "gj", { desc = "Personal preference" })
vim.keymap.set({ "n", "v" }, "k", "gk", { desc = "Personal preference" })
vim.keymap.set("n", "<leader><space>e", "<cmd>lua MiniFiles.open()<CR>", { desc = 'Open Mini.Files' })
vim.keymap.set("n", "<leader>gg", "<cmd>Neogit<CR>", { desc = 'Open Git' })
vim.keymap.set("n", "<leader>cc", "<cmd>Compile<CR>", { desc = 'Compile' })
vim.keymap.set("n", "<leader>ff", "<cmd>Pick files<CR>", { desc = "Open file Picker" })
vim.keymap.set("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>")
vim.keymap.set("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>")
vim.keymap.set("n", "<leader>fg", "<cmd>Pick grep_live<CR>", { desc = "Open Live Grep" })
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set({ "n", "v" }, "<leader>y", "\"+y", { desc = "Copy to system clipboard" })
vim.keymap.set({ "n", "v" }, "<leader>yy", "V\"+y", { desc = "Copy to system clipboard" })
vim.keymap.set({ "n" }, "<leader>p", "\"+p", { desc = "Paste system clipboard" })
vim.keymap.set("v", "<leader>d", "\"_d", { desc = "Delete without copying to buffer" })
vim.keymap.set("n", "<leader>dd", "V\"+d", { desc = "Delete without copying to buffer" })
vim.keymap.set({ 'n', 'i' }, '<C-l>', '<cmd>tabnext<CR>', { desc = "Move to next tab" })
vim.keymap.set({ 'n', 'i' }, '<C-h>', '<cmd>tabprevious<CR>', { desc = "Move to previous tab" })
vim.keymap.set("n", "<C-j>", "<cmd>cnext<CR>zz")
vim.keymap.set("n", "<C-k>", "<cmd>cprev<CR>zz")
vim.keymap.set({ "n", "t" }, "<leader>/", "<cmd>ToggleTerm<CR>")
vim.keymap.set("n", "gx", function()
  local url = vim.fn.expand("<cfile>")
  vim.fn.jobstart({ "xdg-open", url }, { detach = true })
end, { desc = "Open URL with xdg-open" })
